# Set PR owner as Assignee
addAssignees: author

# Set to true to add reviewers to pull requests
addReviewers: true

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  # this is the list of all teammates, it includes the PR owner but it doesn't matter because GH will skip it automatically
  - jamcry
  - Anlerkan
  - yasincaliskan
  # - bilgeyucel
  # - mucahit
  # - edizcelik

# A number of assignees to add to the pull request
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
numberOfAssignees: 0

# A list of keywords to be skipped the process that add reviewers if pull requests include it
skipKeywords:
  - wip
  - draft

filterLabels:
  include:
    - Ready For Review
