# Configuration for Label Actions - https://github.com/dessant/label-actions

# Actions taken when the `Ready For Review` label is added to pull requests
Ready For Review:
  # Post a comment
  comment: This is ready for review @jamcry.
