name: "Label Actions"

on:
  pull_request:
    types: [labeled]
  # issues:
  # types: [labeled, unlabeled]

jobs:
  reaction:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v2
        with:
          github-token: ${{ github.token }}
