on:
  push:
    branches: # only trigger when a commit was pushed to master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm test
      - run: npm run build # compiles with tsc

      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - id: create-gh-release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.publish.outputs.version }}
          release_name: ${{ steps.publish.outputs.version }}

          
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm test