on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm test
      - uses: kentaro-m/auto-assign-action@v1.1.2
      - uses: dessant/label-actions@v2
        with:
          github-token: ${{ github.token }}
          process-only: "prs" # don't trigger for issues


      # this action comments on all PRs, no advanced features
      # so replaced with more advanced label based action: dessant/label-actions@v2
      # - uses: unsplash/comment-on-pr@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     msg: "Automated message @jamcry!"
