on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - id: test-code
        run: npm install
        run: npm test

      - id: auto-assign
        uses: kentaro-m/auto-assign-action@v1.1.2
